version: '3.4'

services:
  services:
    image: "servicesdemodocker2019:1"
    ports: 
      - "8060:8060"
    build:
      context: .
      dockerfile: "Services.DemoDocker2019/Dockerfile"
    environment:
      - ASPNETCORE_URLS=http://+:8060
      - ASPNETCORE_ENVIRONMENT=Development
      - "Consumers:Web=http://docker2019:8050"
  docker2019:
    image: "docker2019:1"
    ports: 
      - "8050:8050"
    build:
      context: .
      dockerfile: Docker2019/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:8050
      - ASPNETCORE_ENVIRONMENT=Development
      - "Consumers:UrlService=http://services:8060/"
